### PR TITLE
Fix #15, fix #16, fix #17

### LINKED ISSUE #15: Populate result.message.markdown
The `IIssue` interface  has properties `MessageText`, `MessageMarkdown`, and `MessageHtml`. The SARIF `Message` object has properties `Text` and `Markdown`. At the moment, the method `SarifIssueReportGenerator.GetResult` only populates `Result.Message.Text`. It could also populate `Result.Message.Markdown`.

### LINKED ISSUE #16: Populate rule metadata with helpUri.
The method `SarifIssueReportGenerator.GetResult` places `IIssue.RuleUrl` into the result's "property bag". SARIF actually has a slot for this: `Tool.Driver.Rules` is an array of SARIF `ReportingDescriptor` objects, and a `ReportingDescriptor` has a `HelpUri` property.

You can find out more about this in the [SARIF Tutorials](https://github.com/microsoft/sarif-tutorials) under the topic [Rule metadata](https://github.com/microsoft/sarif-tutorials/blob/master/docs/2-Basics.md#rule-metadata).

### LINKED ISSUE #17: uriBaseId is a symbolic name, not a path
The method `IIssueExtensions.Location` populates `ArtifactLocation.UriBaseId` with the path to the repo root. `UriBaseId` is actually a symbolic name like `"REPOROOT"` that can be replaced when a user views the file in a SARIF-enabled viewer. You can place the repo root path in the `OriginalUriBaseIds` property of the SARIF `Run` object. The resulting SARIF will look like this:

```
{
  ...
  "runs": [
    {
      "originalUriBaseIds": {
        "REPOROOT": {
          "uri": "file:///C:/source/myproject/"
        },
        "results": [
          {
            "ruleId": "...",
            "locations": [
              {
                "physicalLocation": {
                  "artifactLocation": {
                    "uri": "src/io/file.c",
                    "uriBaseId": "REPOROOT"
                  }
                }
              }
            ]
          }
        ]
      }
    }
  ]
}
```

Unfortunately the [SARIF Tutorials](https://github.com/microsoft/sarif-tutorials) don't yet explain this; there's an issue microsoft/sarif-tutorials#1 to remind me to do it.

### PR DESCRIPTION
**Pull request by lgolding**
#15: Suggestion: populate result.message.markdown.
#16: Suggestion: populate rule metadata with helpUri.
#17: Bug: uriBaseId is a symbolic name, not a path.

@michaelcfanning @pascalberger

### CODE REVIEW

**Comment by lgolding** [comment]
@pascalberger Thank you for the review! I think I've already done the cleanup. I also just pushed another tweak to the tests, verifying the correct values for `result.level` and `result.kind`.

@michaelcfanning and I would be very interested to know how you heard about SARIF, and what made you decide to adopt it. We're delighted to see spontaneous adoption!

**Comment by lgolding** [comment]
@pascalberger Oh, and sorry, just to be clear -- yes, I do think the PR is ready now. You can merge whenever you like.

**Comment by pascalberger** [comment]
@lgolding wrote:
> @michaelcfanning and I would be very interested to know how you heard about SARIF, and what made you decide to adopt it. We're delighted to see spontaneous adoption!

[Cake Issues](https://cakeissues.net/) is an extensible toolkit for issue management inside Cake build script, so having SARIF support seems like a natural fit. This addin provides export issues to SARIF format. I've planned to write another one which allows to import files in SARIF format, which would allow to e.g. run some linter which can create a SARIF compatible file in a CI build, read it and report the issues to the pull request (e.g. as comment in Azure DevOps). 
Honestly no idea where I heard first about SARIF, as it was quite a while ago :)

**Comment by pascalberger** [comment]
@lgolding your changes have been merged, thanks for your contribution 👍

**Pull request merged**
